;;; init.el -- Emacs configuration
;;;
;;; Commentary:
;;;
;;; Use use-package and straight to manage Emacs configuration
;;;
;;; Code:
;;;

;; straight.el to manage package
(eval-when-compile
  ;; custom file
  (setq custom-file (expand-file-name "custom.el" user-emacs-directory))

  (if (file-exists-p custom-file)
      (load custom-file))

  (add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))

  (defvar bootstrap-version)
  (let ((bootstrap-file
         (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
        (bootstrap-version 5))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
          (url-retrieve-synchronously
           "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
           'silent 'inhibit-cookies)
        (goto-char (point-max))
        (eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))

  (defconst secret-el-path (expand-file-name ".secret.el" user-emacs-directory))

  (if(file-exists-p secret-el-path)
      (load-file secret-el-path)
    (defconst secret-wakatime-api-key "")))

;; use package
(straight-use-package 'use-package)


;; ;; 开启 use-package 记录包加载时间
;; ;; see also: https://emacstalk.github.io/post/004/
(setq use-package-verbose t)


;;; Common
(use-package init-common)
(use-package init-my
  :bind
  ("C-c s p" . my/url-proxy-toggle)
  ("C-c s g" . my/generate-buffer))

(use-package init-darwin
  :after init-common-mode
  :if (memq window-system '(mac ns)))

(use-package init-linux
  :after init-common-mode
  :if (memq window-system '(x)))

;;; Appearance
(use-package init-common-mode :defer 1 :after init-common)
;; (use-package init-theme-doom)
;; (use-package init-theme-nano)
(use-package init-theme-bespoke)
(use-package init-screen)

(use-package emojify
  :straight (emojify :host github :repo "iqbalansari/emacs-emojify"
                     :files ("*.el" "data"))
  :commands emojify-mode
  :custom
  (emojify-emoji-styles '(unicode github)))

;; (use-package cnfonts
;;   :straight (cnfonts :host github :repo "tumashu/cnfonts")
;;   :after init-darwin
;;   :custom
;;   (cnfonts--custom-set-fontnames
;;       '(
;;         ("Victor Mono")
;;         ("STKaiti" "Hiragino Sans GB")
;;         ("HanaMinB" "SimSun-ExtB" "MingLiU-ExtB")))
;;
;;   (cnfonts--custom-set-fontsizes
;;         '(
;;           (14  16.5 16.5)
;;           ))
;;   :init
;;   (cnfonts-enable))

;; Auto generated by cnfonts
;; <https://github.com/tumashu/cnfonts>
(when window-system
  (set-face-attribute
   'default nil
   :font (font-spec :name "-*-Victor Mono-normal-normal-normal-*-*-*-*-*-m-0-iso10646-1"
                    :weight 'normal
                    :slant 'normal
                    :size 14.0))
  (dolist (charset '(kana han symbol cjk-misc bopomofo))
    (set-fontset-font
     (frame-parameter nil 'font)
     charset
     (font-spec :name "-*-STKaiti-normal-normal-normal-*-*-*-*-*-p-0-iso10646-1"
                :weight 'normal
                :slant 'normal
                :size 16.5))))

(use-package all-the-icons :straight t)

(use-package ligature
  :straight
  (ligature :host github :repo "mickeynp/ligature.el")
  :after (s org-roam projectile)
  :config
  ;; Enable the "www" ligature in every possible major mode
  (ligature-set-ligatures 't '("www"))
  ;; Enable traditional ligature support in eww-mode, if the
  ;; `variable-pitch' face supports it
  (ligature-set-ligatures 'eww-mode '("ff" "fi" "ffi"))
  ;; Enable all Cascadia Code ligatures in programming modes
  (ligature-set-ligatures 'prog-mode '("|||>" "<|||" "<==>" "<!--" "####" "~~>" "***" "||=" "||>"
                                       ":::" "::=" "=:=" "===" "==>" "=!=" "=>>" "=<<" "=/=" "!=="
                                       "!!." ">=>" ">>=" ">>>" ">>-" ">->" "->>" "-->" "---" "-<<"
                                       "<~~" "<~>" "<*>" "<||" "<|>" "<$>" "<==" "<=>" "<=<" "<->"
                                       "<--" "<-<" "<<=" "<<-" "<<<" "<+>" "</>" "###" "#_(" "..<"
                                       "..." "+++" "/==" "///" "_|_" "www" "&&" "^=" "~~" "~@" "~="
                                       "~>" "~-" "**" "*>" "*/" "||" "|}" "|]" "|=" "|>" "|-" "{|"
                                       "[|" "]#" "::" ":=" ":>" ":<" "$>" "==" "=>" "!=" "!!" ">:"
                                       ">=" ">>" ">-" "-~" "-|" "->" "--" "-<" "<~" "<*" "<|" "<:"
                                       "<$" "<=" "<>" "<-" "<<" "<+" "</" "#{" "#[" "#:" "#=" "#!"
                                       "##" "#(" "#?" "#_" "%%" ".=" ".-" ".." ".?" "+>" "++" "?:"
                                       "?=" "?." "??" ";;" "/*" "/=" "/>" "//" "__" "~~" "(*" "*)"
                                       "\\\\" "://"))
  ;; Enables ligature checks globally in all buffers. You can also do it
  ;; per mode with `ligature-mode'.
  (global-ligature-mode t))

;;; Shell
(use-package exec-path-from-shell
  :straight (exec-path-from-shell :host github :repo "purcell/exec-path-from-shell")
  :init
  (setq exec-path-from-shell-check-startup-files nil)
  (exec-path-from-shell-initialize))

(use-package vterm
  :straight t
  ;; commands to defer
  :commands (vterm vterm-buffer)
  :after multi-vterm
  :hook
  (vterm-mode . (lambda ()
                  (linum-mode -1)
                  (when (>= emacs-major-version 26)
                    (display-line-numbers-mode -1))))
  :config
  (setq vterm-toggle--vterm-buffer-p-function 'vmacs-term-mode-p)
  (defun vmacs-term-mode-p(&optional args)
    (derived-mode-p 'eshell-mode 'term-mode 'shell-mode 'vterm-mode)))

(use-package multi-vterm
  :straight t
  :bind
  ("C-c v v" . multi-vterm)
  ("C-c v P" . multi-vterm-project)
  ("C-c v n" . multi-vterm-next)
  ("C-c v p" . multi-vterm-prev)
  ("C-c v d" . multi-vterm-dedicated-toggle))

;;; Enhance Emacs
(use-package goto-line-preview :straight t
  :bind (("M-g g" . goto-line-preview)))

(use-package which-key
  :straight t
  :hook
  (lsp-mode . lsp-enable-which-key-integration)
  :custom
  (which-key-show-early-on-C-h t)
  :init
  (which-key-mode))

;; (use-package init-helm)
(use-package init-ivy)

(use-package urlview
  :straight (:host github :repo "coldnight/emacs-urlview" :branch "master")
  :bind
  ("C-c u v" . uv/browse-url))

;; Effective
(use-package magit
  :straight (magit :host github :repo "magit/magit")
  :bind
  ("C-c m s" . magit-status)
  ("C-c m p" . magit-push-current)
  ("C-c m c" . magit-branch-checkout)
  ("C-c m b" . magit-branch-and-checkout)
  ("C-c m f" . magit-fetch)
  ("C-c m m" . magit-merge)
  ("C-c m r" . magit-rebase))

(use-package projectile
  :straight t
  :custom
  (projectile-enable-caching t)
  :bind-keymap
  ("C-c p" . projectile-command-map)
  :config
  (projectile-mode +1)
  ;; see https://github.com/syl20bnr/spacemacs/issues/11381#issuecomment-481239700
  (defadvice projectile-project-root (around ignore-remote first activate)
    (unless (file-remote-p default-directory) ad-do-it))
  (setq projectile-globally-ignored-directories
        (append '(".git"
                  ".svn"
                  ".tox"
                  ".venv"
                  ".gradle"
                  ".meghanada"
                  ".clangd"
                  "eln-cache"
                  "out"
                  "repl"
                  "target"
                  "venv")
                projectile-globally-ignored-directories))

  (setq projectile-globally-ignored-files
        (append '(".DS_Store"
                  "*.gz"
                  "*.pyc"
                  "*.jar"
                  "*.tar.gz"
                  "*.tgz"
                  "*.zip"
                  "*.eln"
                  "*.elc"
                  )
                projectile-globally-ignored-files))
  (projectile-register-project-type 'hugo '("config.toml" "archetypes" "content")
                                    :project-file "config.toml"
				    :compile "hugo"
				    :test "open http://localhost:1313/"
				    :run "hugo server -D --disableFastRender --navigateToChanged"))

(use-package company
  :straight t
  :defer 2
  :config
  (global-company-mode))

(use-package company-jedi
  :straight t
  :after company)

;; Programming Tools
(use-package autopair
  :straight (autopair :host github :repo "joaotavora/autopair")
  :defer 2
  :config
  (autopair-global-mode))

(use-package flycheck
  :straight t
  :defer 2
  :config
  (global-flycheck-mode)
  :custom
  ;; .rst 文件禁用 flycheck
  (flycheck-disabled-checkers '(rst grammarly)))

(use-package pos-tip
  :defer 2
  :straight t
  :after flycheck)

(use-package flycheck-pos-tip
;;  :straight (flycheck :host github :repo "flycheck/flycheck-pos-tip")
  :straight t
  :after (flycheck pos-tip)
  :config
  (flycheck-pos-tip-mode))

(use-package posframe :defer 1 :straight t)

(use-package flycheck-swiftlint
  :straight t
  :after flycheck
  :config
  (flycheck-swiftlint-setup))

(use-package aggressive-indent-mode
  :straight t
  :hook
  (emacs-lisp-mode  . aggressive-indent-mode))

;;; Language Server Mode
(use-package init-lsp
  :after (init-common-mode flycheck))

;;; Edit
(use-package whitespace
  :straight whitespace
  :hook
  (prog-mode . whitespace-mode)
  (before-save . delete-trailing-whitespace)
  :custom
  (whitespace-line-column 79)
  (whitespace-style '(face lines-tail))
  (delete-trailing-lines t))

;;; Programming Language Specific
;; Python black
(use-package blacken
  :straight (blacken :host github :repo "pythonic-emacs/blacken")
  :custom
  (blacken-fast-unsafe t)
  :bind
  ("C-c f p" . blacken-buffer))

;; Programming Language Mode
(use-package go-mode
  :straight (go-mode :host github :repo "dominikh/go-mode.el")
  :mode "\\.go\\'"
  :custom
  (gofmt-command (concat usr-bin-path "gofmt"))
  :bind
  ("C-c f g" . gofmt))

(use-package markdown-mode
  :straight t
  :mode
  ("\\.md\\'" . gfm-mode))

;; 设置缩进级别空格数
(defvar-local my/web-mode-offset 2)

(defun my/current-buffer-suffix()
  "Return suffix of current buffer."

  (nth 0 (cdr (split-string (buffer-name) "\\."))))
(use-package web-mode
  :straight t
  :hook
  (web-mode . (lambda()
                (if (string= (my/current-buffer-suffix) "vue")
                    (setq web-mode-style-padding 0
                          web-mode-script-padding 0))

                ;; 设置缩进级别
                (setq web-mode-markup-indent-offset my/web-mode-offset)
                (setq web-mode-css-indent-offset my/web-mode-offset)
                (setq web-mode-code-indent-offset my/web-mode-offset)
                (setq web-mode-attr-indent-offset my/web-mode-offset)))
  :mode
  ("\\.js\\'" . web-mode)
  ("\\.jsx\\'" . web-mode)
  ("\\.vue\\'" . web-mode)
  ("\\.jinja\\'" . web-mode)
  ("\\.ts\\'" . web-mode)
  ("\\.tsx\\'" . web-mode)
  :custom
  ;; JS2 设置缩进
  (js2-basic-offset my/web-mode-offset)
  (js-indent-level my/web-mode-offset)
  (company-tooltip-align-annotations t)

  ;; HTML/XML 缩进
  (sgml-basic-offset my/web-mode-offset))

;; TypeScript
(defun my/setup-tide-mode ()
  "Setup tide mode used in \\<keymap\\>>."
  (interactive)
  (tide-setup)
  (flycheck-mode +1)
  (setq flycheck-check-syntax-automatically '(save mode-enabled))
  (eldoc-mode +1)
  (tide-hl-identifier-mode +1)
  ;; company is an optional dependency. You have to
  ;; install it separately via package-install
  ;; `M-x package-install [ret] company`
  (company-mode +1))

(use-package tide
  :straight t
  :hook
  (before-save . tide-format-before-save)
  (typescript-mode . setup-tide-mode)
  (web-mode .
            (lambda ()
              (when (string-equal "tsx" (file-name-extension buffer-file-name))
                (my/setup-tide-mode))))
  :config
  (flycheck-add-mode 'typescript-tslint 'web-mode)
  :after (web-mode flycheck company))

;; Some useful modes
(use-package swift-mode :straight t
  :mode "\\.swift\'")
;; (use-package indent-guide :straight t)
;; (use-package highlight-indentation :straight t)
(use-package json-mode :straight t
  ;; mode to defer
  :mode "\\.json\\'")
(use-package yaml-mode :straight t
  :mode ("\\.yaml\\'" "\\.yml\\'"))
(use-package less-css-mode :straight t
  ;; mode to defer
  :mode "\\.less\\'")
(use-package gradle-mode :straight t
  :mode "\\.gradle\\'")
(use-package rust-mode :straight t
  :mode "\\.rs\\'")
(use-package htmlize :straight t
  :mode "\\.html\\'")
(use-package php-mode :straight t
  ;; mode to defer
  :mode "\\.php\\'")
(use-package kotlin-mode :straight t
  :mode "\\.kt\\'")
(use-package dockerfile-mode :straight t
  :mode "Dockerfile\\'")
(use-package cmake-mode
  :mode "CMakeLists.txt\\'"
  :straight (:host github :flavor melpa
                   :files ("Auxiliary/*.el" "cmake-mode-pkg.el")
                   :repo "Kitware/CMake"))

;; Enable scala-mode for highlighting, indentation and motion commands
(use-package scala-mode
  :straight t
  :interpreter
    ("scala" . scala-mode))

;; Enable sbt mode for executing sbt commands
(use-package sbt-mode
  :straight t
  :commands sbt-start sbt-command
  :config
  ;; WORKAROUND: https://github.com/ensime/emacs-sbt-mode/issues/31
  ;; allows using SPACE when in the minibuffer
  (substitute-key-definition
   'minibuffer-complete-word
   'self-insert-command
   minibuffer-local-completion-map)
   ;; sbt-supershell kills sbt-mode:  https://github.com/hvesalai/emacs-sbt-mode/issues/152
  (setq sbt:program-options '("-Dsbt.supershell=false")))

;; Org Mode
(use-package init-org
  :after init-common-mode)

;;; Misc
;; speedup
;; M-x esup
(use-package esup :straight t
  :commands esup)

;; backup
(use-package backup-walker
  :straight t
  :defer 3
  :hook
  (before-save . (lambda () (setq buffer-backed-up nil)))
  :custom
  ;; 备份设置
  (make-backup-files t)
  (vc-make-backup-files t)
  ;; 启用版本控制,
  (version-control t)
  ;; 备份最原始的版本两次,记第一次编辑前的文档,和第二次编辑前的文档
  (kept-old-versions 2)
  ;; 备份最新的版本 256 次,理解同上
  (kept-new-versions 256)
  ;; 删掉不属于以上1,2中版本的版本
  (delete-old-versions t)
  ;; 备份设置方法,直接拷贝
  (backup-by-copying t)
  :config
  ;; 设置备份文件的路径
  (defvar-local backup-dir (concat user-emacs-directory "backups") "Backup directory.")
  (if (not (file-exists-p backup-dir))
      (make-directory backup-dir))
  (add-to-list 'backup-directory-alist `(".*" . ,backup-dir))

  ;; tramp for remote edit
  (setq tramp-backup-directory-alist backup-directory-alist))

(use-package leetcode
  :straight (leetcode :host github :repo "kaiwk/leetcode.el")
  :commands leetcode
  :custom
  (leetcode-prefer-language "cpp"))

(if (not (string= secret-wakatime-api-key ""))
    (use-package wakatime-mode
      :straight t
      :defer 4
      :custom
      (wakatime-api-key secret-wakatime-api-key)
      :init
      (global-wakatime-mode)))

(use-package init-optional)
(use-package init-mu4e :commands mu4e)
(use-package init-writing)

(message "*** Emacs loaded in %s with %d garbage collections."
         (format "%.2f seconds"
                 (float-time
                  (time-subtract after-init-time before-init-time))) gcs-done)
;;; init.el ends here
